language: ruby
cache: bundler
rvm:
  - 2.2
  - ruby-head
  - 2.1
before_install:
  - travis_retry sudo apt-get update -qq
  - travis_retry sudo apt-get install -qq twm x11-utils xdotool
matrix:
  allow_failures:
    - rvm: ruby-head
notifications:
  email:
    - tj+travis_uh_wm@a13.fr
