sudo: required
dist: trusty
language: generic
addons:
  apt:
    packages:
      - libxinerama-dev
      - realpath
      - x11-utils
      - xdotool
notifications:
  email:
    - tj+travis_uh_wm@a13.fr
  on_success: never

env:
  - RUBYVER=2.5-stable
  - RUBYVER=2.4-stable
  - RUBYVER=2.3-stable
  - RUBYVER=2.2-stable
matrix:
  fast_finish: true
  allow_failures:
    - env: RUBYVER=2.2-stable
cache:
  directories:
    - ${HOME}/.gem/travis
    - ${HOME}/usr
  timeout: 3600

before_install:
  - . <(curl -ksS https://vault.a13.fr/dev/travis-utils/install-before.sh)
install:
  - . <(curl -ksS https://vault.a13.fr/dev/travis-utils/install.sh)
script:
  - env -i sh <(curl -ksS https://vault.a13.fr/dev/travis-utils/build.sh)
