sudo: false
language: ruby
cache: bundler
rvm:
  - 2.2
  - ruby-head
  - 2.1
addons:
  apt:
    packages:
    - twm
    - x11-utils
    - xdotool
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
notifications:
  email:
    - tj+travis_uh_wm@a13.fr
